### PR TITLE
refactor(mvn): drop more `antenna-`-prefixes

### PR DESCRIPTION
**Pull request by maxhbr**

### CODE REVIEW

**Comment by sschuberth** [comment]
Commit message nit: s/anntenna- preifxes/anntenna-prefixes/

**Comment by maxhbr** [comment]
@sschuberth the commit message is now fixed

**Comment by sschuberth** [comment]
@maxhbr but you didn't (force) push yet, did you? Also, I noticed "reafctor" also has a typo.

**Comment by maxhbr** [comment]
I had force pushed:

**Comment by sschuberth** [comment]
But https://github.com/eclipse/antenna/pull/200/commits/ecd46d85d77384698adc231b7c79167ff7f9ac22 still says "preifxes " :wink:

**Comment by blaumeiser-at-bosch** [comment]
@maxhbr: The commit message is still broken, and it is antenna, not anntenna :-)

**Comment by maxhbr** [comment]
OK, that could be a record for most typos in a commit message.

**Pull request merged**
