### PR TITLE
fix(gradle): correct test set up

### PR DESCRIPTION
**Pull request by bs-ondem**

### CODE REVIEW

**Comment by bs-ondem** [comment]
@neubs-bsi Please try the build this branch on Windows.

**Comment by bs-ondem** [comment]
@maxhbr Waiting for feedback from @neubs-bsi to be sure that the tests are successful on windows.

**Comment by maxhbr** [comment]
azure build for this PR (with integration tests): https://dev.azure.com/EclipseSW360antenna/EclipseSW360antenna/_build/results?buildId=219

**Comment by neubs-bsi** [comment]
Error isn't occuring anymore on windows

**Comment by bs-ondem** [comment]
@maxhbr This PR can be merged now.

**Pull request merged**
