### PR TITLE
Version defined as commit string

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
- Versions are 1.0.0-SNAPSHOT by default as before
- An explicit version can be created by `mvn package -Drevision=<some revision> -Dchangelist=<some changelist>`
- To also change the version for P2, a few files need to be modified. This is indicated in the top level pom.

Note that this versioning scheme breaks the maven release plugin. Releases now have to be done "by hand" modifying the four locations (top-level-pom + three p2 files) + example projects by hand.

### CODE REVIEW

**Comment by blaumeiser-at-bosch** [comment]
@bs_ondem: Since you are making releases, you should be involved in this PR

**Comment by bs-ondem** [comment]
@Martin-Idel-SI can we squash some commits?

**Comment by Martin-Idel-SI** [comment]
@bs-ondem There you go. Squashed them to one commit.

**Comment by blaumeiser-at-bosch** [comment]
Build ran through except for the standard p2 issue :-(, therefore I merge it

**Pull request merged**
