### PR TITLE
refactor(architecture): rename packages to resolve conflicts

### PR DESCRIPTION
**Pull request by maxhbr**
this does the following refactorings

```
org.eclipse.sw360.antenna.workflow.processors.CoordinatesValidator -> org.eclipse.sw360.antenna.validators.workflow.processors.CoordinatesValidator
org.eclipse.sw360.antenna.workflow.processors.LicenseValidator -> org.eclipse.sw360.antenna.validators.workflow.processors.LicenseValidator
org.eclipse.sw360.antenna.workflow.processors.MatchStateValidator -> org.eclipse.sw360.antenna.validators.workflow.processors.MatchStateValidator
org.eclipse.sw360.antenna.workflow.processors.SecurityIssueValidator -> org.eclipse.sw360.antenna.validators.workflow.processors.SecurityIssueValidator
org.eclipse.sw360.antenna.workflow.processors.AntennaDroolsChecker -> org.eclipse.sw360.antenna.drools.workflow.processors.AntennaDroolsChecker
org.eclipse.sw360.antenna.workflow.processors.SourceValidator -> org.eclipse.sw360.antenna.validators.workflow.processors.SourceValidator
org.eclipse.sw360.antenna.workflow.processors.enricher.ChildJarResolver -> org.eclipse.sw360.antenna.p2.workflow.processors.enricher.ChildJarResolver
org.eclipse.sw360.antenna.workflow.processors.enricher.ManifestResolver -> org.eclipse.sw360.antenna.p2.workflow.processors.enricher.ManifestResolver
org.eclipse.sw360.antenna.workflow.processors.SW360Enricher -> org.eclipse.sw360.antenna.sw360.workflow.processors.SW360Enricher
org.eclipse.sw360.antenna.workflow.processors.SW360Updater -> org.eclipse.sw360.antenna.sw360.workflow.processors.SW360Updater
org.eclipse.sw360.antenna.workflow.analyzers.MvnDependencyTreeAnalyzer -> org.eclipse.sw360.antenna.maven.workflow.analyzers.MvnDependencyTreeAnalyzer
```

and additionally merges two submodules of `p2`.

### CODE REVIEW

**Comment by maxhbr** [comment]
I used the following script for migration:
```
#!/usr/bin/env bash

cd "$(dirname $0)"
ROOT="$(pwd)"


findAll() {
    find "$ROOT" \
         \( -not -iwholename '*.git*' \) \
         -and \
         \( -not -iwholename '*.idea*' \) \
         -and \
         \( -not -iwholename '*target*' \) \
         -and \
         \( -not -iname '*.sh' \) \
         -type f -print0
}

searchForToReplace() {
    local old="$1"
    findAll | xargs -0 grep "$old"
}
applyReplaceToAll() {
    local pattern="s/${1}/g"
    findAll | xargs -0 sed -i "$pattern"
}

cat <<EOF |
org.eclipse.sw360.antenna.workflow.processors.CoordinatesValidator/org.eclipse.sw360.antenna.validators.workflow.processors.CoordinatesValidator
org.eclipse.sw360.antenna.workflow.processors.LicenseValidator/org.eclipse.sw360.antenna.validators.workflow.processors.LicenseValidator
org.eclipse.sw360.antenna.workflow.processors.MatchStateValidator/org.eclipse.sw360.antenna.validators.workflow.processors.MatchStateValidator
org.eclipse.sw360.antenna.workflow.processors.SecurityIssueValidator/org.eclipse.sw360.antenna.validators.workflow.processors.SecurityIssueValidator
org.eclipse.sw360.antenna.workflow.processors.AntennaDroolsChecker/org.eclipse.sw360.antenna.drools.workflow.processors.AntennaDroolsChecker
org.eclipse.sw360.antenna.workflow.processors.SourceValidator/org.eclipse.sw360.antenna.validators.workflow.processors.SourceValidator
org.eclipse.sw360.antenna.workflow.processors.enricher.ChildJarResolver/org.eclipse.sw360.antenna.p2.workflow.processors.enricher.ChildJarResolver
org.eclipse.sw360.antenna.workflow.processors.enricher.ManifestResolver/org.eclipse.sw360.antenna.p2.workflow.processors.enricher.ManifestResolver
org.eclipse.sw360.antenna.workflow.processors.SW360Enricher/org.eclipse.sw360.antenna.sw360.workflow.processors.SW360Enricher
org.eclipse.sw360.antenna.workflow.processors.SW360Updater/org.eclipse.sw360.antenna.sw360.workflow.processors.SW360Updater
org.eclipse.sw360.antenna.workflow.analyzers.MvnDependencyTreeAnalyzer/org.eclipse.sw360.antenna.maven.workflow.analyzers.MvnDependencyTreeAnalyzer
EOF

while read line; do
    old="$(dirname "$line")"
    new="$(basename "$line")"
    echo "### replace $(tput bold)$old$(tput sgr0) by $(tput bold)$new$(tput sgr0)"
    echo "    will be applied to $(tput bold)$(searchForToReplace "$old" | wc -l)$(tput sgr0) files"
    applyReplaceToAll "$line"
done
```

**Comment by maxhbr** [comment]
to find still conflicting packages one can use
```bash
find . -type d -iname main -print | grep -v target | while read main; do (cd $main; find . -type f -iname '*.java' -print) | while read java; do echo "[$(dirname $java | sed 's%./java/%%' | sed 's%/%.%g')]"; done | sort -u | sed -e 's%$% '"$(dirname "$(dirname "$main")" | sed 's%./%%')"'%'; done | sort | grep -v '\[\.\]'| column -t  --table-columns PACKAGE,MODULE --table-right PACKAGE
```

**Comment by maxhbr** [comment]
additional renamings caused by the fixes of the above mentioned collisions:

```
org.eclipse.sw360.antenna.knowledgebase.CSVBasedLicenseKnowledgeBase/org.eclipse.sw360.antenna.knowledgebase.csv.CSVBasedLicenseKnowledgeBase
org.eclipse.sw360.antenna.gradle.GradlePlugin/org.eclipse.sw360.antenna.frontend.gradle.GradlePlugin
org.eclipse.sw360.antenna.workflow.processors.checkers.AbstractComplianceChecker/org.eclipse.sw360.antenna.workflow.stubs.AbstractComplianceChecker
org.eclipse.sw360.antenna.workflow.processors.checkers.AntnenaComplianceException/org.eclipse.sw360.antenna.workflow.stubs.AntnenaComplianceException
org.eclipse.sw360.antenna.workflow.processors.checkers.DefaultPolicyEvaluation/org.eclipse.sw360.antenna.workflow.stubs.DefaultPolicyEvaluation
org.eclipse.sw360.antenna.frontend.AntennaMojoFrontend/org.eclipse.sw360.antenna.frontend.mojo.AntennaMojoFrontend
```

**Comment by blaumeiser-at-bosch** [comment]
@maxhbr: Please rebase

**Comment by maxhbr** [comment]
@blaumeiser-at-bosch is rebased.

**Pull request merged**
