### PR TITLE
Remove travis build script

### PR DESCRIPTION
**Pull request by blaumeiser-at-bosch**
Signed-off-by: Lars Geyer-Blaumeiser <lars.geyer-blaumeiser@bosch.io>

Remove the travis build script because github actions are now running reliably with good speed.

### Request Reviewer
@neubs-bsi @oheger-bosch @bs-ondem 

### Type of Change
*Type of change*:  CI

### How Has This Been Tested?
Regression testing

### Checklist
Must:
- [X] All related issues are referenced in commit messages

### CODE REVIEW

**Comment by neubs-bsi** [comment]
If we remove travis, the link in the read me pointing to the master build should be removed as well

**Comment by blaumeiser-at-bosch** [comment]
> If we remove travis, the link in the read me pointing to the master build should be removed as well

You mean the icon at the top? This is already pointing to the freshly installed master build with Github Actions. The build is triggered on every merge in master branch, it also runs SonarCloud analysis on the current master.

**Comment by neubs-bsi** [comment]
Oh, true, sorry. That's what happens when you have an old branch checked out.

**Comment by blaumeiser-at-bosch** [comment]
> Oh, true, sorry. That's what happens when you have an old branch checked out.

Don't get that. The build triggers, if the HEAD of master changes in the eclipse repository, so if you force push an old state, this is then the current master. I think there is a misunderstanding.

BTW. I enhanced the link in the readme to provide a link to the build action page.

**Pull request merged**
