### PR TITLE
Added Maven Wrapper 3.6.3

### LINKED ISSUE #579: Consider using the Maven wrapper
As Antenna is [sensitive regarding the Maven version](https://github.com/eclipse/antenna#install-and-build-antenna) to be used for building, we should consider using the [Maven wrapper](https://github.com/takari/maven-wrapper) so that the correct Maven version is automatically used.

### PR DESCRIPTION
**Pull request by ohbus**
### Added Maven Wrapper

These files are from Maven wrapper. It works similarly to the Gradle wrapper.

This allows you to run the Maven project without having Maven installed and present on the path. It downloads the correct Maven version if it's not found (as far as I know by default in your user home directory).

The `mvnw` file is for Linux (bash) and the `mvnw.cmd` is for the Windows environment.

Should fix #579

- [x] Maven Binary Version `3.6.3`
- [x] Maven Wrapper Version `0.5.6`

### CODE REVIEW

**Comment by neubs-bsi** [comment]
Hello @ohbus ,
thanks for your contribution. 
As you might have seen in some places, we have a [contribution guideline](https://github.com/eclipse/antenna/blob/master/CONTRIBUTING.md#git-commit-messages). Your commit messages do not describe why the changes are necessary. 
For example: https://github.com/eclipse/antenna/pull/639/commits/295d1ca46115d66802b99a114754a269e51513af
`refactored PR build behavior ` -> why is that better than before or why is it necessary. 

Additionally I would like to ask you, to use the pull request template [that comes with this repository](https://github.com/eclipse/antenna/blob/master/.github/pull_request_template.md). It should have automatically been there when you filed this PR.

**Comment by ohbus** [comment]
Hi @neubs-bsi, as I have linked the corresponding Issue against this Pull request I did not follow the template. 

I apologize for this and would like to amend the necessary changes.

Thanks.

**Comment by neubs-bsi** [comment]
Hello @ohbus 

We don't want merge commits in a PR, rather it's preferred to [rebase](https://git-scm.com/docs/git-rebase) master on the branch of the PR.
Additionally, you have not re-written the commit messages. It is still not obvious why the changes would be better than the way it was before. Please [amend the commit messages](https://linuxize.com/post/change-git-commit-message/#changing-an-older-or-multiple-commits).

**Comment by ohbus** [comment]
@neubs-bsi done with your requests

**Pull request closed without merging**
