### PR TITLE
fix(test): move integration tests to src/integrationtest

### PR DESCRIPTION
**Pull request by maxhbr**

### CODE REVIEW

**Comment by sschuberth** [comment]
I like the general idea of this to make the IDE import with the *default* profile work out-of-the-box, and shift the extra configuration work that needs to be done to the *integration-test* profile. Please also document in the `README.md` what needs to be done in the IDE now to make the *integration-test* work.

**Comment by sschuberth** [comment]
@maxhbr, this is still marked as a draft. Is it ready for review now?

**Comment by maxhbr** [comment]
Wuhu, travis is :green_apple:

**Comment by sschuberth** [comment]
> Wuhu, travis is green_apple

Just because I had retriggered the failing jobs for you :wink:

**Pull request merged**
