### PR TITLE
Fix and update Jenkins

### PR DESCRIPTION
**Pull request by maxhbr**
- [x] TODO: adopt `./Jenkinsfile`
- [ ] fix tests in eclipse jenkins (probably out of scope, not necessary)
- [ ] fix configuration of build job https://ci.eclipse.org/antenna/job/build-pipeline/ to build master again

#### Maven Plugin
add the following to a pom with antenna
```xml
   <pluginRepositories>
     <pluginRepository>
       <id>eclipse-antenna-snapshot</id>
       <url>https://download.eclipse.org/antenna/snapshots/</url>
       <releases>
         <enabled>true</enabled>
       </releases>
       <snapshots>
         <enabled>true</enabled>
       </snapshots>
     </pluginRepository>
   </pluginRepositories>
```
and run `mvn package`.
#### CLI:
or download the cli jar from https://download.eclipse.org/antenna/snapshots/org/eclipse/sw360/antenna/cli/1.0.0-SNAPSHOT/?d and verify that it is working, e.g. via:
```
$java -jar /-mp/cli-1.0.0-20190813.075046-1.jar ./pom.xml
```

### CODE REVIEW

**Comment by maxhbr** [comment]
based on https://github.com/eclipse/antenna/pull/229

**Comment by maxhbr** [comment]
current problem:
```
+ mvn --batch-mode -Dmaven.repo.local=/home/jenkins/workspace/build-pipeline/repository -f /tmp/tmp.vWhTZkn5E5/example-project/pom.xml clean package
[INFO] Scanning for projects...
[...]
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.10/maven-dependency-plugin-2.10.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.10/maven-dependency-plugin-2.10.jar (160 kB at 1.2 MB/s)
[WARNING] The POM for org.eclipse.sw360.antenna:antenna-maven-plugin:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.901 s
[INFO] Finished at: 2019-08-06T16:37:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.eclipse.sw360.antenna:antenna-maven-plugin:1.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.sw360.antenna:antenna-maven-plugin:jar:1.0.0-SNAPSHOT -> [Help 1]
```

**Comment by maxhbr** [comment]
Currently the integration tests fail on the eclipse jenkins, but the tests should succeed on the private jenkins.

**Comment by maxhbr** [comment]
To test that the pushed artifacts work, one can add the following to the example project:
```xml
   <pluginRepositories>
     <pluginRepository>
       <id>eclipse-antenna-snapshot</id>
       <url>https://download.eclipse.org/antenna/snapshots/</url>
       <releases>
         <enabled>true</enabled>
       </releases>
       <snapshots>
         <enabled>true</enabled>
       </snapshots>
     </pluginRepository>
   </pluginRepositories>
```

**Comment by maxhbr** [comment]
the snapshot build is pushed to here: https://download.eclipse.org/antenna/snapshots/org/eclipse/sw360/antenna/

**Comment by maxhbr** [comment]
or download the cli jar from https://download.eclipse.org/antenna/snapshots/org/eclipse/sw360/antenna/cli/1.0.0-SNAPSHOT/?d and verify that it is working, e.g. via:
```
$java -jar /-mp/cli-1.0.0-20190813.075046-1.jar ./pom.xml
```

**Comment by blaumeiser-at-bosch** [comment]
Can you just post the url of the eclipse instance? Thanks!

**Comment by maxhbr** [comment]
https://ci.eclipse.org/antenna/job/build-pipeline/

**Comment by blaumeiser-at-bosch** [comment]
+1 for Antenna Download from Eclipse Download area

**Comment by blaumeiser-at-bosch** [comment]
Internal Jenkins fails in this step:
+ cp -r example-projects/example-project/ /tmp/tmp.YBGzFHMPoc/example-project/
+ mvn --batch-mode -Dmaven.repo.local=/var/jenkins_home/workspace/_maxhbr_fixJenkinsP2RelatedBuild/repository -f /tmp/tmp.YBGzFHMPoc/example-project/pom.xml clean package
----- withMaven Wrapper script -----with
ERROR] Plugin org.eclipse.sw360.antenna:antenna-maven-plugin:1.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.sw360.antenna:antenna-maven-plugin:jar:1.0.0-SNAPSHOT in public (https://repo.bosch-si.com/content/groups/public) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by maxhbr** [comment]
@blaumeiser-at-bosch The jenkins build should be restarted, can you please tell me whether the problem is still present? (I was not able to reproduce it locally)

**Comment by blaumeiser-at-bosch** [comment]
@maxhbr: I restarted the Jenkins build on the internal server, it was successful, but it did only this:
Bildschirmfoto 2019-08-21 um 11 34 48

**Comment by maxhbr** [comment]
can you please run it with tests?

**Pull request merged**
