### PR TITLE
Oheger bosch/sw360/#426 redesign client library api

### PR DESCRIPTION
**Pull request by oheger-bosch**
Issue #426 
This PR is about a redesign of the SW360 client library.

In the current state, an asynchronous API has been introduced by adding an asynchronous adapter interface and implementation for all existing adapter classes. The (existing) synchronous adapters are now implemented in terms of the new asynchronous ones.

With minor exceptions, the methods provided by the adapters have not been changed.

Classes and packages have been moved, so that all classes of the library are now located below the _client_ package.

@neubs-bsi @blaumeiser-at-bosch 

*Type of change*:  
improvements

Tests have been added for the asynchronous adapter implementations; existing tests have been adapted where necessary.

### Checklist
Must:
- [x] All related issues are referenced in commit messages

Optional: *(delete if not applicable)*
- [x] I have provided tests for the changes (if there are changes that need additional tests)

### CODE REVIEW

**Comment by blaumeiser-at-bosch** [comment]
Looks quite structured, I would approve on the spot, if I would understand why there are the code smells which do not match common Java conventions. And I am sure you can make the missing 2.4% :wink:

**Comment by blaumeiser-at-bosch** [comment]
@oheger-bosch: Any reason for this variable to still have a leading underscore? See the 2 remaining Code Smells?

**Comment by blaumeiser-at-bosch** [comment]
👍 

Final question, is the PR ready or what do you want to improve?

**Comment by oheger-bosch** [comment]
Regarding the question whether the PR is ready: I think, the infrastructure to use the library in both synchronous and asynchronous mode is now complete.

Currently, the SW360 adapter interfaces have been taken more or less directly as they are. I would like to review them one by one to make sure that the operations they provide are really generic and cover the typical set of CRUD operations. WDYT, should this be done in this PR or in separate ones? The latter is maybe preferable, as it is easier to discus the changes.

**Comment by blaumeiser-at-bosch** [comment]
> Regarding the question whether the PR is ready: I think, the infrastructure to use the library in both synchronous and asynchronous mode is now complete.
> 
> Currently, the SW360 adapter interfaces have been taken more or less directly as they are. I would like to review them one by one to make sure that the operations they provide are really generic and cover the typical set of CRUD operations. WDYT, should this be done in this PR or in separate ones? The latter is maybe preferable, as it is easier to discus the changes.

I think, two PRs make sense, this PR is extremely difficult to review and more changes do not improve the situation.

**Pull request merged**
